### PR TITLE
Feature/pd 434 design overview

### PR DESCRIPTION
**Pull request by catherine-jones**
dasboard-desktop
dasboard-mobile

### CODE REVIEW

**Comment by halfshark** [comment]
Cool, looks great. Some minor alignment issues I'm catching but we can chat about those tomorrow – easier than explaining it here I guess. OK?

**Comment by joahua** [comment]
Just capturing @halfshark's feedback for service strip changes on index:

- Line weight of KPI title
- Change the link "View {service name}" -> "View Dashboard"
- Updated at {month} {year} -> Last updated {dd month yyyy}

**Comment by elisechant** [comment]
To me i feel the KPI sparklines on desktop changes their thickness. 

I also feel that there is a lot of padding that needs to be tightened up? cc @raabsolutely .

**Comment by joahua** [comment]
@catherine-jones and @raabsolutely, when you're both online can you catch up to log outstanding issues here? Happy to help capture if you'd like.

@elisechant has noted some spacing and sparkline issues but there are a range of other pretty clear issues even on desktop i.e. repeated content in the wrong place. Maybe worth checking the testing env build went OK and everything's been pushed if local doesn't look like this.

image

**Comment by catherine-jones** [comment]
@joahua this branch is in progress so these issues are being worked on but I haven't gotten to them yet

**Comment by catherine-jones** [comment]
desktop
tablet
iphone

**Comment by catherine-jones** [comment]
tablet

**Comment by catherine-jones** [comment]
screen shot 2016-09-23 at 2 43 56 pm
screen shot 2016-09-23 at 3 39 29 pm
Firefox 47 :th

**Comment by catherine-jones** [comment]
screen shot 2016-09-23 at 3 39 29 pm
screen shot 2016-09-23 at 3 39 37 pm

Firefox 47

**Comment by catherine-jones** [comment]
[dashboard-safari.pdf](https://github.com/AusDTO/dto-dashboard/files/488953/dashboard-safari.pdf)
Safaris 9.1.2

**Comment by catherine-jones** [comment]
bs_win10_edge_14 0
bs_win10_edge_14 0 1

Edge 14

**Comment by catherine-jones** [comment]
bs_win7_ie_10 0
bs_win7_ie_10 0 1

IE 10

**Comment by catherine-jones** [comment]
bs_win7_ie_10 0 2
bs_win7_ie_10 0 3
IE 10 looking better

**Pull request merged**
