### PR TITLE
task - implement bootstrap grid to below the line on Show page

### PR DESCRIPTION
**Pull request by elisechant**

### CODE REVIEW

**Comment by catherine-jones** [comment]
@elisechant let's have a chat about this tomorrow I don't think this is the right approach to take

**Comment by catherine-jones** [comment]
@elisechant will pull down and test in the next hour.

**Comment by elisechant** [comment]
@catherine-jones please park testing for now.

**Comment by elisechant** [comment]
Close because cherry picked else where.

**Pull request closed without merging**
