### PR TITLE
Task/pd 839 2fa global styles

### PR DESCRIPTION
**Pull request by catherine-jones**
- overrides for sign in h1 and h2
- overrides for h4
- adjust size of QR code
- overrides weight of label text
- overrides background colour of callout for QR code

### CODE REVIEW

**Comment by catherine-jones** [comment]
- [ ] IE9
- [ ] IE10
- [ ] IE11
- [ ] IE13
- [ ] Edge
- [ ] Chrome/responsive
- [ ] Safari
- [ ] Firefox
- [ ] iphone 5
- [ ] iphone 6
- [ ] iphone 7
- [ ] ipad air
- [ ] ipad mini
- [ ] ipad pro
- [ ] Samsung Galaxy S6
- [ ] Screen reader
- [ ] WAVE

**Comment by elisechant** [comment]
why dont we pull these changes in to master instead?

**Comment by elisechant** [comment]
also, not really styling in here.. ??

**Comment by tobyhede** [comment]
Something has happened to this branch, I think. There are a number of commits from master being reapplied here.

**Comment by tobyhede** [comment]
Oh hang on. This is merging a branch into another branch?

Please don't do that, we should always branch and merge into master, it just gets too complicated otherwise.

**Pull request closed without merging**
