### PR TITLE
PD-679 Use rails assets in production to fingerprint files for caching

### PR DESCRIPTION
**Pull request by elisechant**

### CODE REVIEW

**Comment by elisechant** [comment]
@tobyhede fingerprinting will actually change the filename, because the hash is based on file change not timestamp

**Comment by tobyhede** [comment]
Isn't that what we want?

**Comment by tobyhede** [comment]
view-source_localhost_3000_and_rspec2_-_mock_rails_env_development__using_rspec_-_stack_overflow

**Comment by tobyhede** [comment]
Test in production mode locally, will deploy to testing env to replicate in CF.

**Comment by tobyhede** [comment]
Confirmed on testing. Assets fingerprinting a-ok.

**Comment by elisechant** [comment]
ok cool. happy to push. @tobyhede I moved the assets to lib/assets/ instead of app/assets/ are you happy with that?

**Comment by tobyhede** [comment]
@elisechant Yep, all good.

**Pull request merged**
