### PR TITLE
Refresh dashboard favicons

### PR DESCRIPTION
**Pull request by elisechant**
- includes missing favicons
- adds web manifest file
- apply to 3 layouts

### CODE REVIEW

**Comment by elisechant** [comment]
screen shot 2016-10-13 at 6 10 43 am
🎉

**Comment by tobyhede** [comment]
:100:

**Comment by tobyhede** [comment]
So we can either make the unicorn not production or just close this out.

**Comment by catherine-jones** [comment]
@elisechant @tobyhede maybe we just close this one for now and when we get a chance we can add it to staging enviroments

**Comment by elisechant** [comment]
Reopening because it's still valid. The action should be the swap out the favicon with another cc @phil-banks ideally supply a large format icon.

**Comment by elisechant** [comment]
created a JIRA: https://govausites.atlassian.net/browse/PD-745

**Pull request closed without merging**
