### PR TITLE
Install yarn for circle

### PR DESCRIPTION
**Pull request by tobyhede**

### CODE REVIEW

**Comment by elisechant** [comment]
💯

**Comment by elisechant** [comment]
:shipit:

**Comment by elisechant** [comment]
side not we can drop the `"` around the command on line 9

**Comment by elisechant** [comment]
@tobyhede why did this PR fail earlier? did you "Rebuild without cache" in circle?

**Comment by tobyhede** [comment]
I had done a rebuild without cache, but then it failed because cache. It would be picking up the cache from another build - they are shared. So once this is in, we do the global clean cache again, and then this fix should ensure we dont have the sme npm problems ever again

**Comment by elisechant** [comment]
oh cool. makes sense.

**Pull request merged**
