### PR TITLE
Fix 'generate a new code' and 'try again' in 2FA flow

### PR DESCRIPTION
**Pull request by micapam**
Links to DELETE methods require jquery-ujs which is overkill. 
Just switched out the links & used `button_for`... we can style the buttons to look like links if we want (thoughts?)

### CODE REVIEW

**Comment by tobyhede** [comment]
I thought you could add a method to a link and rails would handle ... 
might have changed

**Comment by micapam** [comment]
You can. But you need jquery-ujs for that (which we don't have). I guess we could include it as a node module?

**Comment by tobyhede** [comment]
Nah, this is fine. Not worth adding the extra KB

**Comment by tobyhede** [comment]
LGTM

**Pull request merged**
