### PR TITLE
Fix for crash in prod env

### PR DESCRIPTION
**Pull request by micapam**
This is ugly as - checking for Rails env in a view :(
However I think until we have feature flags, ugliness is wearable. 
I just want this merged in quick so we don't forget & cause same error on next prod deploy.

### CODE REVIEW

**Comment by elisechant** [comment]
🚢

**Comment by elisechant** [comment]
@micapam maybe we make a task in JIRA or no point to bother?

**Comment by micapam** [comment]
@elisechant I reckon a task in Jira for feature flags would be the one to make ... I can do it ? (in product backlog)

**Comment by elisechant** [comment]
either or, just record the action if action should be taken, if not whatevs

**Pull request merged**
