### PR TITLE
Task/pd 606 implement sass architecture

### PR DESCRIPTION
**Pull request by catherine-jones**

### CODE REVIEW

**Comment by elisechant** [comment]
Let's please make sure we talk about this before merge.

**Comment by tobyhede** [comment]
I am a bit wary of giant refactors like this, especially as we keep seeing regressions in the production app. Any way we can pull into smaller chunks that are easier to test?

**Comment by elisechant** [comment]
Yeah, let's swarm about this one today.

**Comment by elisechant** [comment]
@catherine-jones I think we need to abandon this PR. I'm concerned there are too many mixed concerns of code change and file restructuring for this push.

**Pull request closed without merging**
