### PR TITLE
adds commitizen

### PR DESCRIPTION
**Pull request by elisechant**

### CODE REVIEW

**Comment by elisechant** [comment]
@micapam thoughts?

**Comment by elisechant** [comment]
from Slack: 
"pops a gui to help you write better commit messages, and then plugs in to git hooks to validate that the messages are in the expected shape"

screen shot 2016-12-19 at 9 33 32 am
screen shot 2016-12-19 at 9 32 38 am

**Comment by micapam** [comment]
Looks cool but how about we use this too? https://www.npmjs.com/package/cz-jira-smart-commit

**Comment by elisechant** [comment]
@micapam ohhhh! good idea

**Comment by elisechant** [comment]
also, which commit types we would like, maybe they should marry to JIRA issue types, as in "task", "bug"

**Comment by micapam** [comment]
Sounds good... 'story', 'task', 'bug' ?

**Pull request merged**
